language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

install: true
script: mvn clean package -DskipTests=true

env:
  global:
    - CODECOV_TOKEN=${{CODECOV_TOKEN}}
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
#      -at@yandex.ru
    on_success: never # default: change
    on_failure: always # default: al,ways

services:
  - postgresql

before_install:
- psql -c 'create database job4j_forum;' -U postgres
deploy:
  provider: heroku
  app: powerful-ocean-77296
  api_key:
    secure: 3hqO/jzOPoQ4IpdVqc8v7DcoPvqGBtSoftHwlp6nz7T5GII8w2Rs+dArjEPqvpdP4s90rC8XuW0yQ/WnQDjOf1KFo6aNduIORQgf3cRImTS9S/AT3rIdcI/FKhTyZIbVd2adnGmADQzSkT61a+et9oP4Pgpn5mS4mwmuOHOaqw+sVv1B52gXnEhge/lpeK1YMSGOqI3I1BFWpTlkZHcPaLkRS1Gqpm+MQRO6rudOeIazfn//b0tIS7KjFYiC631HPT6iCz7Pj/f/PzKShQKxafzrbYuRjRk9FqB3MWct2ge53GVcTY4Mvrm2+e8Xru1P1wgihrEtF+wHTvG/NcE9e5vxkhSaVJ3PP1XOoMUdsrSALAnWSqagSY8/3URwUnwgXxjkLFYdU0IG1RdqrxqVEuEY+OFe8SmqqIAKd9Uj8/mrTZkLhQXcNETbqgRMguoXFRDeZbeDC1fK3ocjCy1iOM1VJHwZInSeBmu5nvDzVabtfP87XBmo721XxylrG4+k2ro+Aw+p+aMG87fmgb1VLJ9S9bXw0onY3aDUsvqFqUgwmC7/qxWU2Jzy4M0GkOGrJ5v8WeaZEVFjvyA+tNV5t297KAmIloUltmjkJ3s7UM6FOkDGSoEwE2gni4hXS7JviWnYASu6uqtzwKZVVnr3VIn9/hQDsN7aKhEYkTZOoK8=