language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

install: true
script: mvn clean package -DskipTests=true

env:
  global:
    - CODECOV_TOKEN=${{CODECOV_TOKEN}}
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
#      -at@yandex.ru
    on_success: never # default: change
    on_failure: always # default: al,ways

services:
  - postgresql

before_install:
- psql -c 'create database job4j_forum;' -U postgres
deploy:
  provider: heroku
  app: powerful-ocean-77296
  api_key:
    secure: kCFn4DAPHS85UvFr7QbiCaTf97kPFvVDmo03TaOE/CkHOvzu8qqAyyDy4pUIrx5gStZPavSC9pE+wkQpVd9KSWv+fciSR+ATUCr+SNJoZjFyVhwxJeYi/Z8Si7ly++0Lz5bcLN6WmXw5imoX/QTCAHauNjY7B3isPzdH3P9dZEErGvDHTB79eSUQh/8ocqyi2KK/Z1QyZjqsxQykqY5JCmsUljE4Mkni9hUkjtjeLoTIGF7VwjkGMovcjf8U3mH7E99bhqT0kbrb0jjK1YiFNW4YGsmaSCNIyrp4ezSpWN5aIKK4lpxYv50wGsJuwMNRFprIkojeVnUuTJZGeyVusheoS6wOjim7Kr6ebGPSVRg2ZEQFCaB8sOHJ8h+FQ9D3C6ZbeQfrDJmeStq3DYTPFymnpK0yE7xjSdbnygqYiRFpWTgYZdxbVA61xBUB/qGCKcMCW5LqWX//jlrx4bfBo1xggEvG7IpIxIU/d25gGxO4tPs/zO+88JkzGBpwmB0YO+v+4FEL5zB2T/pk9WafqGezObDoEePH3jp6yHaQkRdcWKwSlH7EAMWxiiEoK3GBK8OTRsDmz3Lapxdv8OBH+W7IImtGEuImYXzd5l+648TXpQRtgtzR4eDvmseEagdeTzc++T448LrYGDAZchUWSqAmybi1ffIZ12PxaGCkEWI=
