language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

install: true
script: mvn clean package -DskipTests=true

env:
  global:
    - CODECOV_TOKEN=${{CODECOV_TOKEN}}
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
#      -at@yandex.ru
    on_success: never # default: change
    on_failure: always # default: al,ways

services:
  - postgresql

before_install:
- psql -c 'create database job4j_forum;' -U postgres
deploy:
  provider: heroku
  app: powerful-ocean-77296
  api_key:
    secure: m92zoA1IYUnyW2ovnl81aBmHz6XDUj362IjgvrXRVtd9AsQFsB1ACAb916NunEtIHFG0zeonjmrcewU2QIhyiIrBwB6Jo9vfhyHLO/c/Aab42tiykcHDHcTtkhKDJWbzI2HOCnY6B8I74KiqgoydEiLFyGPKGPHQV/gT0YDq9hQ0rVAz691JeZC71OWki+u/TtM+q1tI7UksngcQbTFrBfvOFt3UfUOtla71E4s4EJfX6IxrewZmIUHjUXyo2uPXxgHP8p1Kk1MJp/HR2wbHjFxIBeRzsa8uZPmopmnDj8utHeRsf0WODUquUxSYwhnCgROR2x59rh6Z+GNoPnhmhsSUiXgxcHMBQbCRQJ7QoJ9MhKd8KHpj9OY5J/dbdqAzRORl1ggpnBVmlA4KT1Z69VwI9NHl7wmILPW6YBUv7iMOlZ0KkrLSp+QWzOXgIHvyf3iZ5CQaGy0QG6NohQjIqWGyRs0vFmnFtLXjKt9ws2F/wR/HYFWEPESn+NkQ1llOCSa9tCoxDY++spvbp9gHHCL5CdLKDqn36GcAk59f1o2RGDMaISUL3FsZCJU0oG4N2WZH4NEbHEoPWgj6YuuXvjHVFdAxgAOhEdyGGpecOrrrqj0cloDQHYU6Os2nAX/aZNy5SK8qS+5ielMDjyBX0U9V8wH9y2HmMzNznB5HhWw=
